name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/image_16.png
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/arrow_left_8_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/images/image_16.png
  - assets/vectors/arrow_left_2_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/images/image_16.png
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/arrow_left_3_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/images/image_16.png
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/arrow_left_9_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/calendar_2_x2.svg
  - assets/vectors/seat_313_x2.svg
  - assets/vectors/seat_341_x2.svg
  - assets/vectors/seat_314_x2.svg
  - assets/vectors/seat_4_x2.svg
  - assets/vectors/seat_122_x2.svg
  - assets/vectors/seat_272_x2.svg
  - assets/vectors/seat_211_x2.svg
  - assets/vectors/wifi_6_x2.svg
  - assets/vectors/ellipse_260_x2.svg
  - assets/vectors/seat_61_x2.svg
  - assets/vectors/seat_301_x2.svg
  - assets/vectors/ellipse_2631_x2.svg
  - assets/vectors/ticket_x2.svg
  - assets/vectors/seat_451_x2.svg
  - assets/vectors/base_2_x2.svg
  - assets/vectors/seat_432_x2.svg
  - assets/vectors/seat_81_x2.svg
  - assets/vectors/seat_292_x2.svg
  - assets/vectors/seat_2_x2.svg
  - assets/vectors/seat_392_x2.svg
  - assets/vectors/seat_51_x2.svg
  - assets/vectors/seat_20_x2.svg
  - assets/vectors/seat_352_x2.svg
  - assets/vectors/seat_171_x2.svg
  - assets/vectors/buy_1_x2.svg
  - assets/vectors/seat_462_x2.svg
  - assets/vectors/calendar_4_x2.svg
  - assets/vectors/ellipse_262_x2.svg
  - assets/vectors/cellular_connection_6_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/seat_40_x2.svg
  - assets/vectors/seat_231_x2.svg
  - assets/vectors/seat_192_x2.svg
  - assets/vectors/seat_372_x2.svg
  - assets/vectors/seat_32_x2.svg
  - assets/vectors/seat_1_x2.svg
  - assets/vectors/seat_481_x2.svg
  - assets/vectors/seat_72_x2.svg
  - assets/vectors/seat_32_x2.svg
  - assets/vectors/arrow_left_5_x2.svg
  - assets/vectors/seat_47_x2.svg
  - assets/vectors/seat_44_x2.svg
  - assets/vectors/seat_281_x2.svg
  - assets/vectors/seat_132_x2.svg
  - assets/vectors/seat_241_x2.svg
  - assets/vectors/seat_33_x2.svg
  - assets/vectors/seat_36_x2.svg
  - assets/vectors/seat_161_x2.svg
  - assets/vectors/seat_141_x2.svg
  - assets/vectors/seat_382_x2.svg
  - assets/vectors/seat_181_x2.svg
  - assets/vectors/seat_22_x2.svg
  - assets/vectors/seat_25_x2.svg
  - assets/vectors/container_4_x2.svg
  - assets/vectors/seat_152_x2.svg
  - assets/vectors/seat_42_x2.svg
  - assets/vectors/seat_91_x2.svg
  - assets/vectors/seat_111_x2.svg
  - assets/vectors/seat_101_x2.svg
  - assets/vectors/seat_262_x2.svg
  - assets/vectors/seat_411_x2.svg
  - assets/vectors/buy_2_x2.svg
  - assets/vectors/seat_12_x2.svg
  - assets/vectors/seat_302_x2.svg
  - assets/vectors/seat_232_x2.svg
  - assets/vectors/seat_191_x2.svg
  - assets/vectors/seat_38_x2.svg
  - assets/vectors/seat_221_x2.svg
  - assets/vectors/seat_11_x2.svg
  - assets/vectors/seat_121_x2.svg
  - assets/vectors/seat_8_x2.svg
  - assets/vectors/cellular_connection_1_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/seat_92_x2.svg
  - assets/vectors/seat_315_x2.svg
  - assets/vectors/seat_31_x2.svg
  - assets/vectors/container_11_x2.svg
  - assets/vectors/seat_172_x2.svg
  - assets/vectors/seat_431_x2.svg
  - assets/vectors/seat_202_x2.svg
  - assets/vectors/seat_412_x2.svg
  - assets/vectors/seat_472_x2.svg
  - assets/vectors/ellipse_2621_x2.svg
  - assets/vectors/seat_282_x2.svg
  - assets/vectors/arrow_left_7_x2.svg
  - assets/vectors/seat_16_x2.svg
  - assets/vectors/seat_29_x2.svg
  - assets/vectors/seat_461_x2.svg
  - assets/vectors/seat_351_x2.svg
  - assets/vectors/seat_13_x2.svg
  - assets/vectors/seat_45_x2.svg
  - assets/vectors/seat_41_x2.svg
  - assets/vectors/seat_271_x2.svg
  - assets/vectors/ellipse_2632_x2.svg
  - assets/vectors/seat_26_x2.svg
  - assets/vectors/seat_102_x2.svg
  - assets/vectors/seat_441_x2.svg
  - assets/vectors/seat_71_x2.svg
  - assets/vectors/seat_48_x2.svg
  - assets/vectors/seat_21_x2.svg
  - assets/vectors/seat_24_x2.svg
  - assets/vectors/seat_18_x2.svg
  - assets/vectors/ticket_1_x2.svg
  - assets/vectors/seat_322_x2.svg
  - assets/vectors/ellipse_2601_x2.svg
  - assets/vectors/calendar_5_x2.svg
  - assets/vectors/seat_251_x2.svg
  - assets/vectors/battery_5_x2.svg
  - assets/vectors/seat_342_x2.svg
  - assets/vectors/seat_62_x2.svg
  - assets/vectors/seat_37_x2.svg
  - assets/vectors/base_1_x2.svg
  - assets/vectors/seat_15_x2.svg
  - assets/vectors/seat_422_x2.svg
  - assets/vectors/seat_212_x2.svg
  - assets/vectors/seat_5_x2.svg
  - assets/vectors/seat_311_x2.svg
  - assets/vectors/seat_391_x2.svg
  - assets/vectors/seat_331_x2.svg
  - assets/vectors/seat_14_x2.svg
  - assets/vectors/seat_361_x2.svg
  - assets/vectors/calendar_1_x2.svg
  - assets/vectors/seat_402_x2.svg
  - assets/images/image_1.jpeg
  - assets/images/image.png
  - assets/images/image_2.png
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/cellular_connection_2_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/tab_bar_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/container_10_x2.svg
  - assets/vectors/stroke_1_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/arrow_left_1_x2.svg
  - assets/images/rectangle_756.jpeg
  - assets/images/rectangle_7531.jpeg
  - assets/images/rectangle_7501.jpeg
  - assets/images/rectangle_7561.png
  - assets/images/rectangle_7503.jpeg
  - assets/images/rectangle_753.jpeg
  - assets/images/rectangle_7581.jpeg
  - assets/images/rectangle_761.jpeg
  - assets/images/rectangle_759.png
  - assets/images/rectangle_750.jpeg
  - assets/images/rectangle_757.jpeg
  - assets/images/rectangle_7504.jpeg
  - assets/images/rectangle_762.png
  - assets/images/rectangle_755.jpeg
  - assets/images/rectangle_7502.jpeg
  - assets/images/rectangle_760.jpeg
  - assets/images/rectangle_7551.jpeg
  - assets/images/rectangle_7505.jpeg
  - assets/images/rectangle_758.jpeg
  - assets/vectors/cellular_connection_x2.svg
  - assets/vectors/tab_bar_1_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/icon_magnifyingglass_1_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/sf_symbol_microphone_x2.svg
  - assets/vectors/cellular_connection_4_x2.svg
  - assets/vectors/seat_82_x2.svg
  - assets/vectors/seat_332_x2.svg
  - assets/vectors/seat_242_x2.svg
  - assets/vectors/arrow_left_x2.svg
  - assets/vectors/seat_28_x2.svg
  - assets/vectors/seat_291_x2.svg
  - assets/vectors/ellipse_2622_x2.svg
  - assets/vectors/seat_112_x2.svg
  - assets/vectors/calendar_x2.svg
  - assets/vectors/seat_362_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/seat_34_x2.svg
  - assets/vectors/seat_19_x2.svg
  - assets/vectors/ticket_3_x2.svg
  - assets/vectors/seat_35_x2.svg
  - assets/vectors/container_8_x2.svg
  - assets/vectors/seat_162_x2.svg
  - assets/vectors/calendar_3_x2.svg
  - assets/vectors/seat_39_x2.svg
  - assets/vectors/seat_7_x2.svg
  - assets/vectors/seat_312_x2.svg
  - assets/vectors/seat_10_x2.svg
  - assets/vectors/seat_43_x2.svg
  - assets/vectors/seat_381_x2.svg
  - assets/vectors/battery_6_x2.svg
  - assets/vectors/seat_17_x2.svg
  - assets/vectors/seat_131_x2.svg
  - assets/vectors/seat_46_x2.svg
  - assets/vectors/seat_3_x2.svg
  - assets/vectors/seat_201_x2.svg
  - assets/vectors/seat_12_x2.svg
  - assets/vectors/seat_23_x2.svg
  - assets/vectors/seat_222_x2.svg
  - assets/vectors/base_x2.svg
  - assets/vectors/seat_41_x2.svg
  - assets/vectors/seat_42_x2.svg
  - assets/vectors/seat_6_x2.svg
  - assets/vectors/seat_442_x2.svg
  - assets/vectors/seat_252_x2.svg
  - assets/vectors/seat_11_x2.svg
  - assets/vectors/seat_261_x2.svg
  - assets/vectors/buy_x2.svg
  - assets/vectors/seat_452_x2.svg
  - assets/vectors/seat_9_x2.svg
  - assets/vectors/seat_371_x2.svg
  - assets/vectors/ellipse_263_x2.svg
  - assets/vectors/seat_22_x2.svg
  - assets/vectors/ellipse_2602_x2.svg
  - assets/vectors/seat_471_x2.svg
  - assets/vectors/seat_27_x2.svg
  - assets/vectors/seat_482_x2.svg
  - assets/vectors/seat_31_x2.svg
  - assets/vectors/seat_421_x2.svg
  - assets/vectors/seat_151_x2.svg
  - assets/vectors/seat_30_x2.svg
  - assets/vectors/seat_52_x2.svg
  - assets/vectors/seat_321_x2.svg
  - assets/vectors/seat_182_x2.svg
  - assets/vectors/seat_21_x2.svg
  - assets/vectors/seat_142_x2.svg
  - assets/vectors/seat_401_x2.svg
  - assets/images/image.png
  - assets/images/image_2.png
  - assets/images/image_1.jpeg
  - assets/vectors/battery_x2.svg
  - assets/vectors/cellular_connection_3_x2.svg
  - assets/vectors/container_9_x2.svg
  - assets/vectors/container_7_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/arrow_left_4_x2.svg
  - assets/vectors/container_3_x2.svg
  - assets/vectors/tab_bar_3_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/stroke_x2.svg
  - assets/images/image_1.jpeg
  - assets/images/image_2.png
  - assets/images/image.png
  - assets/vectors/container_1_x2.svg
  - assets/vectors/tab_bar_2_x2.svg
  - assets/vectors/stroke_2_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/cellular_connection_5_x2.svg
  - assets/vectors/arrow_left_6_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/container_5_x2.svg
  - assets/vectors/container_6_x2.svg
  - assets/vectors/wifi_2_x2.svg

